version: '3.4'

services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      GAMEMODE: creative
      DIFFICULTY: normal
      ALLOW-CHEATS: true
    ports:
      - 19132:19132/udp
    volumes:
      - /mindcraft:/data
    stdin_open: true
    tty: true

volumes:
  bds: {}
